<?
require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/header.php");
$APPLICATION->SetTitle("Каталог");
?>
<main>
	<div class="section suggest nav-section card-page">
		<div class="container">
			<? $APPLICATION->IncludeComponent(
				"bitrix:breadcrumb",
				"planar",
				array(
					"START_FROM" => "0",
					"PATH" => "",
					"SITE_ID" => "s1",
					"COMPONENT_TEMPLATE" => "planar"
				),
				false
			); ?>
			<div class="section__wrapper false">
				<? $APPLICATION->IncludeComponent(
					"bitrix:catalog",
					"planar",
					array(
						"ACTION_VARIABLE" => "action",
						"ADD_ELEMENT_CHAIN" => "Y",
						"ADD_PICT_PROP" => "-",
						"ADD_PROPERTIES_TO_BASKET" => "N",
						"ADD_SECTIONS_CHAIN" => "Y",
						"AJAX_MODE" => "N",
						"AJAX_OPTION_ADDITIONAL" => "",
						"AJAX_OPTION_HISTORY" => "N",
						"AJAX_OPTION_JUMP" => "N",
						"AJAX_OPTION_STYLE" => "Y",
						"BASKET_URL" => "",
						"CACHE_FILTER" => "N",
						"CACHE_GROUPS" => "Y",
						"CACHE_TIME" => "36000000",
						"CACHE_TYPE" => "A",
						"COMPATIBLE_MODE" => "N",
						"DETAIL_ADD_DETAIL_TO_SLIDER" => "N",
						"DETAIL_BACKGROUND_IMAGE" => "-",
						"DETAIL_BRAND_USE" => "N",
						"DETAIL_BROWSER_TITLE" => "NAME",
						"DETAIL_CHECK_SECTION_ID_VARIABLE" => "N",
						"DETAIL_DETAIL_PICTURE_MODE" => array("POPUP", "MAGNIFIER"),
						"DETAIL_DISPLAY_NAME" => "Y",
						"DETAIL_DISPLAY_PREVIEW_TEXT_MODE" => "E",
						"DETAIL_IMAGE_RESOLUTION" => "16by9",
						"DETAIL_META_DESCRIPTION" => "-",
						"DETAIL_META_KEYWORDS" => "-",
						"DETAIL_PRODUCT_INFO_BLOCK_ORDER" => "sku,props",
						"DETAIL_PRODUCT_PAY_BLOCK_ORDER" => "rating,price,priceRanges,quantityLimit,quantity,buttons",
						"DETAIL_SET_CANONICAL_URL" => "N",
						"DETAIL_SHOW_POPULAR" => "Y",
						"DETAIL_SHOW_SLIDER" => "N",
						"DETAIL_SHOW_VIEWED" => "Y",
						"DETAIL_STRICT_SECTION_CHECK" => "N",
						"DETAIL_USE_COMMENTS" => "N",
						"DETAIL_USE_VOTE_RATING" => "N",
						"DISABLE_INIT_JS_IN_COMPONENT" => "N",
						"DISPLAY_BOTTOM_PAGER" => "Y",
						"DISPLAY_TOP_PAGER" => "N",
						"ELEMENT_SORT_FIELD" => "sort",
						"ELEMENT_SORT_FIELD2" => "id",
						"ELEMENT_SORT_ORDER" => "asc",
						"ELEMENT_SORT_ORDER2" => "desc",
						"FILTER_HIDE_ON_MOBILE" => "N",
						"FILTER_VIEW_MODE" => "VERTICAL",
						"IBLOCK_ID" => "19",
						"IBLOCK_TYPE" => "content",
						"INCLUDE_SUBSECTIONS" => "N",
						"INSTANT_RELOAD" => "N",
						"LABEL_PROP" => array(),
						"LAZY_LOAD" => "N",
						"LINE_ELEMENT_COUNT" => "3",
						"LINK_ELEMENTS_URL" => "link.php?PARENT_ELEMENT_ID=#ELEMENT_ID#",
						"LINK_IBLOCK_ID" => "",
						"LINK_IBLOCK_TYPE" => "",
						"LINK_PROPERTY_SID" => "",
						"LIST_BROWSER_TITLE" => "NAME",
						"LIST_ENLARGE_PRODUCT" => "STRICT",
						"LIST_META_DESCRIPTION" => "-",
						"LIST_META_KEYWORDS" => "-",
						"LIST_PRODUCT_BLOCKS_ORDER" => "price,props,sku,quantityLimit,quantity,buttons",
						"LIST_PRODUCT_ROW_VARIANTS" => "[{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false}]",
						"LIST_SHOW_SLIDER" => "Y",
						"LIST_SLIDER_INTERVAL" => "3000",
						"LIST_SLIDER_PROGRESS" => "N",
						"LOAD_ON_SCROLL" => "N",
						"MESSAGE_404" => "",
						"MESS_BTN_ADD_TO_BASKET" => "",
						"MESS_BTN_BUY" => "",
						"MESS_BTN_COMPARE" => "",
						"MESS_BTN_DETAIL" => "",
						"MESS_BTN_LAZY_LOAD" => "Показать ещё",
						"MESS_BTN_SUBSCRIBE" => "",
						"MESS_NOT_AVAILABLE" => "",
						"MESS_NOT_AVAILABLE_SERVICE" => "",
						"PAGER_BASE_LINK_ENABLE" => "N",
						"PAGER_DESC_NUMBERING" => "N",
						"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
						"PAGER_SHOW_ALL" => "N",
						"PAGER_SHOW_ALWAYS" => "N",
						"PAGER_TEMPLATE" => ".default",
						"PAGER_TITLE" => "Товары",
						"PAGE_ELEMENT_COUNT" => "30",
						"PARTIAL_PRODUCT_PROPERTIES" => "N",
						"PRICE_CODE" => array(),
						"PRICE_VAT_INCLUDE" => "Y",
						"PRICE_VAT_SHOW_VALUE" => "N",
						"PRODUCT_ID_VARIABLE" => "id",
						"PRODUCT_PROPS_VARIABLE" => "prop",
						"PRODUCT_QUANTITY_VARIABLE" => "quantity",
						"SEARCH_CHECK_DATES" => "Y",
						"SEARCH_NO_WORD_LOGIC" => "Y",
						"SEARCH_PAGE_RESULT_COUNT" => "50",
						"SEARCH_RESTART" => "N",
						"SEARCH_USE_LANGUAGE_GUESS" => "Y",
						"SEARCH_USE_SEARCH_RESULT_ORDER" => "N",
						"SECTIONS_HIDE_SECTION_NAME" => "N",
						"SECTIONS_MODE" => "Y",
						"SECTIONS_SHOW_PARENT_NAME" => "Y",
						"SECTIONS_VIEW_MODE" => "LIST",
						"SECTION_BACKGROUND_IMAGE" => "-",
						"SECTION_COUNT_ELEMENTS" => "N",
						"SECTION_ID_VARIABLE" => "SECTION_ID",
						"SECTION_TOP_DEPTH" => "1",
						"SEF_FOLDER" => "/catalog/",
						"SEF_MODE" => "Y",
						"SEF_URL_TEMPLATES" => array("compare" => "compare.php?action=#ACTION_CODE#", "element" => "#SECTION_CODE_PATH#/#ELEMENT_CODE#/", "section" => "#SECTION_CODE_PATH#/", "sections" => "", "smart_filter" => "#SECTION_CODE_PATH#/filter/#SMART_FILTER_PATH#/apply/"),
						"SET_LAST_MODIFIED" => "N",
						"SET_STATUS_404" => "Y",
						"SET_TITLE" => "Y",
						"SHOW_404" => "Y",
						"FILE_404" => "/404.php",
						"SHOW_DEACTIVATED" => "N",
						"SHOW_PRICE_COUNT" => "1",
						"SHOW_SKU_DESCRIPTION" => "N",
						"SHOW_TOP_ELEMENTS" => "N",
						"SIDEBAR_DETAIL_SHOW" => "N",
						"SIDEBAR_PATH" => "",
						"SIDEBAR_SECTION_SHOW" => "Y",
						"TEMPLATE_THEME" => "blue",
						"TOP_ELEMENT_COUNT" => "9",
						"TOP_ELEMENT_SORT_FIELD" => "sort",
						"TOP_ELEMENT_SORT_FIELD2" => "id",
						"TOP_ELEMENT_SORT_ORDER" => "asc",
						"TOP_ELEMENT_SORT_ORDER2" => "desc",
						"TOP_ENLARGE_PRODUCT" => "STRICT",
						"TOP_LINE_ELEMENT_COUNT" => "3",
						"TOP_PRODUCT_BLOCKS_ORDER" => "price,props,sku,quantityLimit,quantity,buttons",
						"TOP_PRODUCT_ROW_VARIANTS" => "[{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false}]",
						"TOP_SHOW_SLIDER" => "N",
						"TOP_SLIDER_INTERVAL" => "3000",
						"TOP_SLIDER_PROGRESS" => "N",
						"TOP_VIEW_MODE" => "SECTION",
						"USER_CONSENT" => "N",
						"USER_CONSENT_ID" => "0",
						"USER_CONSENT_IS_CHECKED" => "Y",
						"USER_CONSENT_IS_LOADED" => "N",
						"USE_COMPARE" => "N",
						"USE_ELEMENT_COUNTER" => "Y",
						"USE_ENHANCED_ECOMMERCE" => "N",
						"USE_FILTER" => "N",
						"USE_MAIN_ELEMENT_SECTION" => "N",
						"USE_PRICE_COUNT" => "N",
						"USE_PRODUCT_QUANTITY" => "N",
						"USE_STORE" => "N",
						"VARIABLE_ALIASES" => array("compare" => array("ACTION_CODE" => "action",),)
					)
				); ?>
			</div>
		</div>
	</div>
</main>
<? require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/footer.php"); ?>